#- name: recommendation
#  command: java -jar target/recommend-0.0.1-SNAPSHOT.jar ./conf/conf.properties
#  stdout_logfile: log/production.log
#  env: RECOMMENDATION_PORT="40%(process_num)02d"
#  startsecs: 5
[]
